owner: Redon-Tech
repo: status

sites:
  - name: Website
    url: https://redon.tech
  - name: Server Panel
    url: https://panel.redon.tech
  - name: Content Delivery Network
    url: https://cdn.redon.tech
  - name: Node 0
    url: https://node0.redon.tech:8080
    expectedStatusCodes:
      - 401
  - name: Node 4
    url: https://node4.redon.tech:8080
    expectedStatusCodes:
      - 401
  - name: Node 5
    url: https://node5.redon.tech:8080
    expectedStatusCodes:
      - 401
  - name: Email Server
    url: https://mail.redon.tech


status-website:
  cname: status.redon.tech
  favicon: https://avatars.githubusercontent.com/u/60410737
  logoUrl: https://avatars.githubusercontent.com/u/60410737
  name: Redon Tech
  introTitle: "**Redon Tech**"
  introMessage: This website provides a quick and easy way to view the status of the services we host.
  themeUrl: https://status.redon.tech/redon-tech-theme.css
  navbar:
    - title: Home
      href: https://redon.tech/
    - title: Status
      href: /


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
