owner: Redon-Tech
repo: status

sites:
  - name: Website
    url: https://redon.tech
  - name: Panel
    url: https://panel.redon.tech
  - name: Giga
    url: giga.redon.tech
    type: globalping
    location: utah
    check: "tcp-ping"
  - name: Mega
    url: mega.redon.tech
    type: globalping
    location: utah
    check: "tcp-ping"
  - name: Wooden
    url: wooden.redon.tech
    type: globalping
    location: utah
    check: "tcp-ping"
  - name: 4D
    url: https://forms.redon.tech
  - name: Mail
    url: https://mail.redon.tech


status-website:
  cname: status.redon.tech
  favicon: https://avatars.githubusercontent.com/u/60410737
  logoUrl: https://avatars.githubusercontent.com/u/60410737
  name: Redon Tech
  introTitle: "**Redon Tech**"
  introMessage: This website provides a quick and easy way to view the status of the services we host.
  themeUrl: https://status.redon.tech/redon-tech-theme.css
  navbar:
    - title: Home
      href: https://redon.tech/
    - title: Status
      href: /


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
